//! Static file handlers.

use axum::{Router, routing::get_service};
use tower_http::services::ServeDir;

/// Builds the static-file router.
pub fn create_static_router() -> Router {
    Router::new()
        // JS, WASM, and CSS generated by Leptos.
        .nest_service("/pkg", get_service(ServeDir::new("target/site/pkg")))
        // Other static assets.
        .nest_service("/assets", get_service(ServeDir::new("target/site/assets")))
}
