[package]
name = "web"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain = { path = "../../domain" }
infra = { path = "../infra" }
chrono = { workspace = true, features = ["serde"] }
topcoat.workspace = true

[build-dependencies]
topcoat = { workspace = true, default-features = false, features = ["tailwind"] }
