[package]
name = "server"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
default-run = "site-server"

[[bin]]
name = "site-server"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
domain = { path = "../../domain" }
infra = { path = "../infra" }
web = { path = "../web" }
httpdate.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
topcoat.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
