[package]
name = "domain"
version.workspace = true
authors.workspace = true
description = "Core domain logic and business rules for blog application"
edition.workspace = true

[dependencies]
# Core dependencies for domain logic
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Async support for use cases
tokio = { version = "1", features = ["rt"] }
futures = "0.3"
async-trait = "0.1"

# Shared types
shared = { path = "../shared" }

# Logging
log = "0.4"

[dev-dependencies]
rstest = "0.26"
tokio-test = "0.4"
