use crate::components::PageMetadata;
use crate::routes::not_found::NotFoundPage;
use crate::{SITE_NAME, build_site_url};
#[cfg(feature = "ssr")]
use axum::http::StatusCode;
#[cfg(feature = "ssr")]
use domain::PageKey;
use domain::StaticPageDocument;
use domain::{
    build_static_page_canonical_path, build_static_page_description, build_static_page_title,
};
#[cfg(feature = "ssr")]
use infra::DynArtifactReader;
use leptos::prelude::*;
#[cfg(feature = "ssr")]
use leptos_axum::ResponseOptions;

#[server]
pub async fn get_about_page_document() -> Result<Option<StaticPageDocument>, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let artifact_reader = use_context::<DynArtifactReader>()
            .ok_or_else(|| ServerFnError::new("artifact reader context is missing"))?;
        let snapshot = artifact_reader.snapshot().await?;
        let page = PageKey::new("about".to_string())
            .map_err(|error| ServerFnError::new(error.to_string()))?;
        let artifact = match snapshot.read_page_document(&page).await {
            Ok(artifact) => artifact,
            Err(error) if error.is_not_found() => return Ok(None),
            Err(error) => return Err(error.into()),
        };

        Ok(Some(domain::build_static_page_document(&artifact)?))
    }

    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::new(
            "get_about_page_document is only available during SSR",
        ))
    }
}

#[component]
fn AboutPageContent(document: StaticPageDocument) -> impl IntoView {
    let title = document.title;
    let html = document.html;

    view! {
        <div class="mx-auto grid min-h-full w-full max-w-[var(--site-content-width)] gap-8 px-4 py-8 text-left sm:px-6 sm:py-12">
            <section class="flex min-h-64 items-center justify-center rounded-2xl border border-border/70 bg-gradient-to-br from-card via-card to-secondary/70 p-8 text-center shadow-[0_18px_42px_rgb(0_0_0/0.24)] sm:min-h-80">
                <div class="grid max-w-xl gap-3 rounded-xl border border-border/60 bg-background/20 p-6 shadow-[0_10px_28px_rgb(0_0_0/0.22)] sm:p-8">
                    <p class="m-0 text-sm tracking-[0.16em] text-muted-foreground uppercase">
                        {"Page"}
                    </p>
                    <h1 class="m-0 text-3xl leading-tight font-bold text-primary after:mx-auto after:mt-3 after:block after:h-1 after:w-12 after:rounded-full after:bg-primary sm:text-4xl">
                        {title}
                    </h1>
                </div>
            </section>

            // Artifact HTML is generated by the private publisher pipeline, which escapes raw
            // HTML from markdown and neutralizes unsafe anchor href schemes before writing the
            // artifact.
            <article
                class="content-prose mx-auto w-full max-w-3xl rounded-xl border border-border/80 bg-card p-6 shadow-[0_12px_32px_rgb(0_0_0/0.22)] sm:p-8"
                inner_html=html
            ></article>
        </div>
    }
}

#[component]
pub fn AboutPage() -> impl IntoView {
    let about_page = Resource::<Result<Option<StaticPageDocument>, String>>::new_blocking(
        || (),
        move |_| async move {
            get_about_page_document()
                .await
                .map_err(|error| error.to_string())
        },
    );

    view! {
        <Suspense fallback=|| {
            view! {
                <PageMetadata
                    title=format!("About | {SITE_NAME}")
                    description="About ページです。"
                    canonical_url=build_site_url("/about")
                />
                <div class="mx-auto my-8 w-[calc(100%-2rem)] max-w-[var(--site-content-width)] rounded-xl bg-secondary p-8 text-center text-muted-foreground">
                    "ページを読み込み中..."
                </div>
            }
        }>
            {move || match about_page.get() {
                Some(Ok(Some(document))) => {
                    let page_title = build_static_page_title(&document, SITE_NAME);
                    let page_description = build_static_page_description(&document);
                    let canonical_url = build_site_url(
                        &build_static_page_canonical_path(&document),
                    );

                    view! {
                        <PageMetadata title=page_title description=page_description canonical_url />
                        <AboutPageContent document />
                    }
                        .into_any()
                }
                Some(Ok(None)) => {
                    mark_not_found_response();
                    view! { <NotFoundPage /> }.into_any()
                }
                Some(Err(error)) => {
                    mark_internal_server_error_response();
                    view! {
                        <div class="mx-auto my-8 w-[calc(100%-2rem)] max-w-[var(--site-content-width)] rounded-xl bg-secondary p-8 text-center text-muted-foreground">
                            {format!("ページの読み込みに失敗しました: {error}")}
                        </div>
                    }
                        .into_any()
                }
                None => view! { <div></div> }.into_any(),
            }}
        </Suspense>
    }
}

#[cfg(feature = "ssr")]
fn mark_not_found_response() {
    if let Some(response) = use_context::<ResponseOptions>() {
        response.set_status(StatusCode::NOT_FOUND);
    }
}

#[cfg(not(feature = "ssr"))]
fn mark_not_found_response() {}

#[cfg(feature = "ssr")]
fn mark_internal_server_error_response() {
    if let Some(response) = use_context::<ResponseOptions>() {
        response.set_status(StatusCode::INTERNAL_SERVER_ERROR);
    }
}

#[cfg(not(feature = "ssr"))]
fn mark_internal_server_error_response() {}
