use crate::components::PageMetadata;
use crate::routes::not_found::NotFoundPage;
use crate::{SITE_NAME, build_site_url};
#[cfg(feature = "ssr")]
use axum::http::StatusCode;
use domain::PageKey;
use domain::StaticPageDocument;
use domain::{
    build_static_page_canonical_path, build_static_page_description, build_static_page_title,
};
#[cfg(feature = "ssr")]
use infra::DynArtifactReader;
use leptos::prelude::*;
#[cfg(feature = "ssr")]
use leptos_axum::ResponseOptions;
use stylance::import_style;

import_style!(about_style, "about.module.scss");

#[server]
pub async fn get_about_page_document() -> Result<Option<StaticPageDocument>, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let artifact_reader = use_context::<DynArtifactReader>()
            .ok_or_else(|| ServerFnError::new("artifact reader context is missing"))?;
        let page = PageKey::new("about".to_string())
            .map_err(|error| ServerFnError::new(error.to_string()))?;
        let artifact = match artifact_reader.read_page_document(&page).await {
            Ok(artifact) => artifact,
            Err(error) if error.is_not_found() => return Ok(None),
            Err(error) => return Err(error.into()),
        };

        Ok(Some(domain::build_static_page_document(&artifact)?))
    }

    #[cfg(not(feature = "ssr"))]
    {
        Err(ServerFnError::new(
            "get_about_page_document is only available during SSR",
        ))
    }
}

#[component]
fn AboutPageContent(document: StaticPageDocument) -> impl IntoView {
    let title = document.title;
    let html = document.html;

    view! {
        <div class=about_style::about_page>
            <section class=about_style::hero_section>
                <div class=about_style::hero_content>
                    <p class=about_style::eyebrow>{"Page"}</p>
                    <h1>{title}</h1>
                </div>
            </section>

            <section class=about_style::content_section>
                // Artifact HTML is generated by the private publisher pipeline, which escapes raw
                // HTML from markdown and neutralizes unsafe anchor href schemes before writing the
                // artifact.
                <article class=about_style::content_card inner_html=html></article>
            </section>
        </div>
    }
}

#[component]
pub fn AboutPage() -> impl IntoView {
    let fallback_document = StaticPageDocument {
        page: PageKey::new("about".to_string()).expect("about is a valid page key"),
        title: "About".to_string(),
        description: Some("About ページです。".to_string()),
        html: String::new(),
    };
    let fallback_document_for_metadata = fallback_document.clone();
    let about_page = Resource::<Result<Option<StaticPageDocument>, String>>::new(
        || (),
        move |_| async move {
            get_about_page_document()
                .await
                .map_err(|error| error.to_string())
        },
    );

    view! {
        <Suspense fallback=move || {
            let page_title = build_static_page_title(&fallback_document_for_metadata, SITE_NAME);
            let page_description =
                build_static_page_description(&fallback_document_for_metadata);
            let canonical_url = build_site_url(
                &build_static_page_canonical_path(&fallback_document_for_metadata),
            );

            view! { <PageMetadata title=page_title description=page_description canonical_url /> }
        }>
            {move || match about_page.get() {
                Some(Ok(Some(document))) => {
                    let page_title = build_static_page_title(&document, SITE_NAME);
                    let page_description = build_static_page_description(&document);
                    let canonical_url = build_site_url(
                        &build_static_page_canonical_path(&document),
                    );

                    view! {
                        <PageMetadata title=page_title description=page_description canonical_url />
                    }
                        .into_any()
                }
                Some(Ok(None)) => {
                    let page_title = format!(
                        "ページが見つかりませんでした | {SITE_NAME}",
                    );
                    let page_description = "ページが見つかりませんでした。"
                        .to_string();
                    let canonical_url = build_site_url("/");

                    view! {
                        <PageMetadata title=page_title description=page_description canonical_url />
                    }
                        .into_any()
                }
                Some(Err(_)) => {
                    let page_title = format!("About の読み込みに失敗しました | {SITE_NAME}");
                    let page_description =
                        "About ページの読み込みに失敗しました。時間をおいて再度お試しください。"
                            .to_string();
                    let canonical_url = build_site_url(
                        &build_static_page_canonical_path(&fallback_document),
                    );

                    view! {
                        <PageMetadata title=page_title description=page_description canonical_url />
                    }
                        .into_any()
                }
                None => {
                    let page_title = build_static_page_title(&fallback_document, SITE_NAME);
                    let page_description = build_static_page_description(&fallback_document);
                    let canonical_url = build_site_url(
                        &build_static_page_canonical_path(&fallback_document),
                    );

                    view! {
                        <PageMetadata title=page_title description=page_description canonical_url />
                    }
                        .into_any()
                }
            }}
        </Suspense>

        <Suspense fallback=|| {
            view! { <div class=about_style::loading>"ページを読み込み中..."</div> }
        }>
            {move || match about_page.get() {
                Some(Ok(Some(document))) => view! { <AboutPageContent document /> }.into_any(),
                Some(Ok(None)) => {
                    mark_not_found_response();
                    view! { <NotFoundPage /> }.into_any()
                }
                Some(Err(error)) => {
                    view! {
                        <div class=about_style::error>
                            {format!("ページの読み込みに失敗しました: {error}")}
                        </div>
                    }
                        .into_any()
                }
                None => view! { <div class=about_style::loading></div> }.into_any(),
            }}
        </Suspense>
    }
}

#[cfg(feature = "ssr")]
fn mark_not_found_response() {
    if let Some(response) = use_context::<ResponseOptions>() {
        response.set_status(StatusCode::NOT_FOUND);
    }
}

#[cfg(not(feature = "ssr"))]
fn mark_not_found_response() {}
