use crate::components::PageMetadata;
use crate::routes::not_found::NotFoundPage;
use crate::{SITE_NAME, build_site_url};
#[cfg(feature = "ssr")]
use axum::http::StatusCode;
use domain::ArticlePageDocument;
#[cfg(feature = "ssr")]
use domain::{Category, Slug, build_article_page_document, find_article_summary};
use domain::{
    build_article_page_canonical_path, build_article_page_description, build_article_page_title,
};
#[cfg(feature = "ssr")]
use infra::DynArtifactReader;
use leptos::prelude::*;
#[cfg(feature = "ssr")]
use leptos_axum::ResponseOptions;
use leptos_router::{hooks::use_params_map, params::ParamsMap};
#[cfg(feature = "ssr")]
use std::str::FromStr;
use stylance::import_style;

import_style!(article_style, "article.module.scss");

#[server]
pub async fn get_article_page_document(
    category: String,
    slug: String,
) -> Result<Option<ArticlePageDocument>, ServerFnError> {
    #[cfg(feature = "ssr")]
    {
        let artifact_reader = use_context::<DynArtifactReader>()
            .ok_or_else(|| ServerFnError::new("artifact reader context is missing"))?;
        let category = match Category::from_str(&category) {
            Ok(category) => category,
            Err(_) => return Ok(None),
        };
        let slug = match Slug::new(normalize_article_slug_param(&slug).to_string()) {
            Ok(slug) => slug,
            Err(_) => return Ok(None),
        };
        let article_index = artifact_reader.read_article_index().await?;
        let Some(summary) = find_article_summary(&article_index, &category, &slug) else {
            return Ok(None);
        };
        let html = match artifact_reader.read_article_html(&category, &slug).await {
            Ok(html) => html,
            Err(error) if error.is_not_found() => return Ok(None),
            Err(error) => return Err(error.into()),
        };

        Ok(Some(build_article_page_document(summary, &html)?))
    }

    #[cfg(not(feature = "ssr"))]
    {
        let _ = category;
        let _ = slug;
        Err(ServerFnError::new(
            "get_article_page_document is only available during SSR",
        ))
    }
}

#[component]
fn ArticlePageContent(document: ArticlePageDocument) -> impl IntoView {
    let page_title = build_article_page_title(&document, SITE_NAME);
    let page_description = build_article_page_description(&document);
    let canonical_url = build_site_url(&build_article_page_canonical_path(&document));
    let title = document.article.title.as_str().to_string();
    let category = document.article.category_display_name;
    let created_at = document.article.created_at;
    let updated_at = document.article.updated_at;
    let description = document.article.description;
    let tags = document.article.tags;
    let has_tags = !tags.is_empty();
    let html = document.html;

    view! {
        <PageMetadata
            title=page_title
            description=page_description
            canonical_url
            og_type="article"
        />

        <article class=article_style::article_page>
            <header class=article_style::article_header>
                <p class=article_style::article_category>{category}</p>
                <h1 class=article_style::article_title>{title}</h1>
                <p class=article_style::article_dates>
                    {format!("公開 {} / 更新 {}", created_at, updated_at)}
                </p>
                {description
                    .map(|description| {
                        view! { <p class=article_style::article_summary>{description}</p> }
                    })}
                <Show when=move || has_tags fallback=|| ()>
                    <ul class=article_style::tag_list>
                        {tags
                            .iter()
                            .map(|tag| {
                                view! { <li class=article_style::tag>{format!("#{tag}")}</li> }
                            })
                            .collect_view()}
                    </ul>
                </Show>
            </header>

            // Artifact HTML is generated by the private publisher pipeline, which escapes raw
            // HTML from markdown before writing the artifact.
            <div class=article_style::article_body inner_html=html></div>
        </article>
    }
}

#[component]
pub fn ArticlePage() -> impl IntoView {
    let params = use_params_map();
    let article_params = move || {
        params.with(|params: &ParamsMap| {
            (
                params.get("category").unwrap_or_default(),
                params.get("slug").unwrap_or_default(),
            )
        })
    };
    let article_page = Resource::<Result<Option<ArticlePageDocument>, String>>::new(
        article_params,
        move |(category, slug)| async move {
            if category.is_empty() || slug.is_empty() {
                return Ok(None);
            }

            get_article_page_document(category, slug)
                .await
                .map_err(|error| error.to_string())
        },
    );

    view! {
        <Suspense fallback=|| {
            view! { <div class=article_style::loading>"記事を読み込み中..."</div> }
        }>
            {move || match article_page.get() {
                Some(Ok(Some(document))) => view! { <ArticlePageContent document /> }.into_any(),
                Some(Ok(None)) => {
                    mark_not_found_response();
                    view! { <NotFoundPage /> }.into_any()
                }
                Some(Err(error)) => {
                    view! {
                        <div class=article_style::error>
                            {format!("記事の読み込みに失敗しました: {error}")}
                        </div>
                    }
                        .into_any()
                }
                None => view! { <div class=article_style::loading></div> }.into_any(),
            }}
        </Suspense>
    }
}

#[cfg(feature = "ssr")]
fn mark_not_found_response() {
    if let Some(response) = use_context::<ResponseOptions>() {
        response.set_status(StatusCode::NOT_FOUND);
    }
}

#[cfg(not(feature = "ssr"))]
fn mark_not_found_response() {}

#[cfg(feature = "ssr")]
fn normalize_article_slug_param(slug: &str) -> &str {
    slug.strip_suffix(".html").unwrap_or(slug)
}
