name: Notion Data Upload

on:
  workflow_dispatch: # enable manual trigger
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  DATABASE_ID: ${{ secrets.DATABASE_ID }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenSSL tool
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config libssl-dev

      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test project
        run: cargo test -p notion_api -- --ignored

      - name: Build and Run the notion_api binary
        run: cargo run -p notion_api --release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}

      - name: Upload files to S3
        run: aws s3 sync crates/notion_api/dist s3://${{ secrets.S3_BUCKET }} --delete
